<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-3NQPI56" name="com.myshopify.tests.TC001_LoginIntoApplication" tests="2" failures="1" timestamp="27 Apr 2020 16:58:58 GMT" time="11.715" errors="0">
  <testcase name="TestStep01_UserSubmitLoginDetails" time="0.376" classname="com.myshopify.tests.TC001_LoginIntoApplication"/>
  <testcase name="TestStep02_UserSearchTheProduct" time="11.339" classname="com.myshopify.tests.TC001_LoginIntoApplication">
    <failure type="java.lang.AssertionError" message="FAILED: Element &#039;icon_search&#039; not found on the SearchPage !!!">
      <![CDATA[java.lang.AssertionError: FAILED: Element 'icon_search' not found on the SearchPage !!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.myshopify.getpageobjects.GetPage.element(GetPage.java:65)
	at com.myshopify.getpageobjects.GetPage.element(GetPage.java:44)
	at com.myshopify.actions.SearchPageAction.clickOnSearchIcon(SearchPageAction.java:25)
	at com.myshopify.tests.TC001_LoginIntoApplication.TestStep02_UserSearchTheProduct(TC001_LoginIntoApplication.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TestStep02_UserSearchTheProduct -->
</testsuite> <!-- com.myshopify.tests.TC001_LoginIntoApplication -->
